### ISSUE TITLE
IRC relay doesn't work when bot joins existing channel(s)

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#10]
When joining existing IRC channel Messages from IRC are not relayed (server to IRC is fine). Joining new channels or disconnecting users and running irc:reconnect it Works correctly again

Also would be Nice With a status/reply for the bungeecord window when the irc Client has reconnected after running irc:reconnect

(this does not work in version 1.6.1 either)

**Comment by geNAZt** [comment]
For the Bug mentioned here i dont have the Problem on EsperNet. I am always online (ZNC Bouncer) and can write in IRC and the Bot writes it into Minecraft.

Even when the Chat (BungeeCord) restarts
