### ISSUE TITLE
Doesn't work on 1 Server

### ISSUE THREAD

**Issue by kenogs** [geNAZt/CloudChat#104]
So i have 3 servers. On 2 of them the plugin works, but on the third (the main/hub server) it doesn't worked. I looked over the config but there is nothing different. 
On all servers i have the 2 plugins (CloudChatBukkit and Yamler-Bukkit). 

Does any plugin interrupt CloudChat?
What i am supposed to do?

**Comment by geNAZt** [comment]
Logs please

**Comment by kenogs** [comment]
latest circumstances have disposed of the problem (not solved, but it is not a problem anymore)
