### ISSUE TITLE
BungeePerms Compatibility 

### ISSUE THREAD

**Issue by BaluMonster** [geNAZt/CloudChat#106]
For some reason CloudChat doesn't get permissions from bungee/bukkit.
I'm using BungeePerms

**Comment by slebu** [comment]
I have the same problem with GroupManager

**Comment by geNAZt** [comment]
BungeePerms is not supported. Groupmanager should work. If not provide logs please.

**Comment by BaluMonster** [comment]
New version of BungeePerms (2.4.0) supports bukkit superperms. Now cloudchat can get permissions
