### ISSUE TITLE
[Feature] IRC color code support in MC

### ISSUE THREAD

**Issue by frdmn** [geNAZt/CloudChat#26]
At the moment:

![bildschirmfoto 2014-01-05 um 02 13 33](https://f.cloud.github.com/assets/944459/1845830/b8695a50-75a6-11e3-85b5-b0117523b3f6.png)

looks ingame like:

![bildschirmfoto 2014-01-05 um 02 13 46](https://f.cloud.github.com/assets/944459/1845829/b45c2f3c-75a6-11e3-8bbd-8517ff75dcaa.png)

Would be nice to have [IRC color character](http://stackoverflow.com/a/13382032) support.

**Comment by geNAZt** [comment]
The color is wrong. It needs to be \u00033 and not \u000303. Just get rid of the 0 and it should be ok
