### ISSUE TITLE
Does not run whois when players join channel after bot(?)

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#29]
15:59:40 [INFO] [CloudChat] Citaborg joined IRC
16:07:59 [INFO] [CloudChat]  geNAZt joined IRC

no entries for "Whois got resolved" for any of them...

Players in the channel on join (like the bot itself) gets resolved
15:58:48 [INFO] [CloudChat] Bot joined #citaborg
15:58:49 [INFO] [CloudChat] Whois got resolved: CitaborgBot -> null

**Comment by geNAZt** [comment]
Have you updated to the latest dev ? (the last commit should have fixed that)

**Comment by Citaborg** [comment]
Works With latest dev... Good work, man!
