### ISSUE TITLE
[Feature] list participants of a specific channel

### ISSUE THREAD

**Issue by frdmn** [geNAZt/CloudChat#30]
`/channelinfo <channel>` or something would be nice to see who is participating in a specific channel

**Comment by frdmn** [comment]
Doesn't that conflict with the `/list` command of the Bungee/Spigot plugin to list the users on the server?

**Comment by geNAZt** [comment]
nope. cloudchat will not let through any commands it catched. maybe this should be able to be "DoNotBind"ed

**Comment by Citaborg** [comment]
Yes, Let the list command be not bindable :-)
