### ISSUE TITLE
Would be nice to "Delay" server joined to fight joined/left SPAMming

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#31]
Maybe not show/log if the join is unsuccessful (or something)
Banned players With autoreconnect and if the lobby is Down gives a lot of joined and left server Messages to IRC (and log)

**Comment by geNAZt** [comment]
yes thats correct. the problem about that is i have to delay the join messages about 1-2 seconds (which is pretty much) and can lead to the fact that people can write before they joined (in the chat ofc).

Maybe i can work around that with a additional Bungee Event. I have to look if i can make this work. But you know me... I get anything to work :D
