### ISSUE TITLE
[Enhancement] Don´t overwrite the bukkit Chat

### ISSUE THREAD

**Issue by Slind14** [geNAZt/CloudChat#34]
Hey,

I would like to use herochat for the per server chat with pwn filter. As I have a nice setup with it. But the problem ist that CloundChat overwrites it. So it would need a enhancement that it is possible to focus **none** chat. Is this something you might add ?

**Comment by geNAZt** [comment]
You can ignore those Servers in the config.yml. And no a Feature to support multiple Chat handlers along CloudChat is not planned.

**Comment by Slind14** [comment]
would it be possible to disable cloudchat as global chat plugin and only use the private chats.
