### ISSUE TITLE
[Enhancement] Autocomplete in Global Chat

### ISSUE THREAD

**Issue by Slind14** [geNAZt/CloudChat#35]
Hey,

the autocomplete works fine with /msg. But it doesn´t work in the currently focused chat. So without any command. Would it be possible to add this ?

**Comment by geNAZt** [comment]
Well currently thats not possible inside BungeeCord. I opened an Issue for BungeeCord https://github.com/SpigotMC/BungeeCord/issues/807. We must wait till this is fixed

**Comment by geNAZt** [comment]
So the TabComplete has been added in BungeeCord today. I will add it to CloudChat this weekend

**Comment by Slind14** [comment]
:)

**Comment by geNAZt** [comment]
Implemented in 8.1.0
