### ISSUE TITLE
[Enhancement] Use the server.properties server-name and server-id

### ISSUE THREAD

**Issue by Slind14** [geNAZt/CloudChat#36]
Add some placeholders for the "server-name" and "server-id" form the server.properties. Leter they can be used as a prefix. 

Server A:
server-id: A
server-name alpha

Server B:
server-id: B
server-name beta

So a message from a player who is on server b could like this:
-B- Player: Why is snow white ?
or like this
[Beta] Player: What happend to the sun its a squere ?

**Comment by geNAZt** [comment]
Since when are server-id and server-name part of the server.properties ? You have the %server format in the Channels YML to get the bungeecord Name for the Server. But it does not support aliases for Servers. Maybe i will add a little Config which allows you to set some Server name Settings

**Comment by Slind14** [comment]
atleast since 1.4.8

**Comment by geNAZt** [comment]
Well i cant find those Properties...

http://minecraft-de.gamepedia.com/Server.properties

**Comment by Slind14** [comment]
copied out of my testservers server.properties which runs on 1.6.4

http://hastebin.com/fuyitufodi.hs

**Comment by geNAZt** [comment]
Well i have this server.properties in 1.6.2-R0.1

http://hastebin.com/rujikukoqu.properties

A Servername but no ID.

**Comment by Slind14** [comment]
mhh is it possible that a plugin adds it or that it is not generated by default ?

**Comment by geNAZt** [comment]
Yes that is possible

**Comment by Slind14** [comment]
ok, than it might be added from a plugin
