### ISSUE TITLE
Spambot detection (AntiBot example)

### ISSUE THREAD

**Issue by geNAZt** [geNAZt/CloudChat#37]
Let a User not write for a configurable Time. After that time "unlock" the User so he can write. 

This should prevent most Spambots since they join => write => leave in 1-2 Seconds. 

Another option should be to disable chat completly in some Servers (like lobbies).

**Comment by craftpimp** [comment]
Yes this would be great, disabling the chat for my hub server!

**Comment by geNAZt** [comment]
You can use the config.yml DontHandleForServers in that case

**Comment by geNAZt** [comment]
Implemented in http://bamboo.cube-space.net/browse/MC-CC-102/artifact/JOB1/CloudChat/CloudChat.jar
