### ISSUE TITLE
Private Mode

### ISSUE THREAD

**Issue by geNAZt** [geNAZt/CloudChat#38]
Let CloudChat pass all Chats without handling them. If a /<channel> <message> command comes in let this be handled via CloudChat.

This is meant for Staff Chats which should be based upon CloudChat but bukkit should handle the Chat itself.

**Comment by Sir-Will** [comment]
<3

**Comment by geNAZt** [comment]
Implemented in http://bamboo.cube-space.net/browse/MC-CC-102/artifact/JOB1/CloudChat/CloudChat.jar

**Comment by Slind14** [comment]
that was fast, thanks
