### ISSUE TITLE
"Strange" default messages

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#40]
What is the {click} stuff in the Messages? Like

```
PlayerJoin: '&8[&2%channel_short&8]&r %prefix%nick{click:playerMenu}%suffix&r joined the Server'
```

In my setup it makes Things look like this (on IRC)

![capture](https://f.cloud.github.com/assets/3041020/1867071/1bd318c2-7847-11e3-9552-8f1c4bbfedf3.PNG)
(see the player joined Message)

**Comment by geNAZt** [comment]
Yeah that shouldnt be so. The {click:playerMenu} is the new Syntax for the Onclick Menu when you click on a Playername inside the Chat (it displays a little Menu for quick access to mute / messsage).

The IRC Relay should be fixed..... Its a bit strange :D
