### ISSUE TITLE
Channel join on player join

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#41]
Seems its trying to join the same channel a couple of times on player join. 

```
11:01:36 [INFO] [Citaborg] <-> ServerConnector [citaworld] has connected
11:01:36 [INFO] [CloudChat] Loading PlayerDatabase for Citaborg
11:01:36 [INFO] [CloudChat] Citaborg tried to join Channel citaworld
11:01:36 [INFO] [CloudChat] Player Citaborg entered Channel citaworld
11:01:36 [INFO] [CloudChat] Citaborg tried to join Channel citaworld
11:01:36 [INFO] [CloudChat] Player Citaborg is already in the Channel citaworld
```

**Comment by geNAZt** [comment]
This is indented since the Player first has the 

JoinedChannel: 
- citaworld 

entry and the Channel citaworld is a Forced channel (correct ?). So it first joins alle Channel from the JoinedChannel list and after that it joins all forced.
