### ISSUE TITLE
[Feature] Toggle join/quit messages per channel

### ISSUE THREAD

**Issue by frdmn** [geNAZt/CloudChat#50]
To avoid duplicate messages. For example:

```
[G] [Owner]frdmn joined the Server
[GU] [Owner]frdmn joined the Server
[A] [Owner]frdmn joined the Server
[D] [Owner]frdmn joined the Server
```

**Comment by geNAZt** [comment]
From what do you have that ? Ingame Players only get the message once per Player (even if the Players match multiple channels)
