### ISSUE TITLE
[Enhancement] Configurable Nickname Prefix/Preface + /nickoff command

### ISSUE THREAD

**Issue by Absentee23** [geNAZt/CloudChat#51]
I like to let some of my players use nicknames for various reasons, however there is no way to tell WHEN they are using nicknames. For example, my current setup which uses EssentialsChat prefixes nicknames with ~ so nicknames appear like "~Nickname." This prefix is also configurable. This allows at a glance to know if someone is using a nickname to impersonate someone else/an admin/etc. I'd like to see this added.

Along with this should be an easy way to clear your nickname, such as /nickoff, as nicknaming yourself your minecraft name isn't a good solution and would then make the prefix appear even in front of your real name.

These are the only things this plugin seems to be missing for me :+1: Thanks!

**Comment by geNAZt** [comment]
http://jenkins.cube-space.net/job/CloudChat/42/; First part (nickname prefixes)
http://jenkins.cube-space.net/job/CloudChat/44/; Second part ("/nick off", "/nick [playername] off" removes the Nickname)
