### ISSUE TITLE
[Bug] No chat appearing

### ISSUE THREAD

**Issue by Absentee23** [geNAZt/CloudChat#52]
I had it working for a bit, but after a restart, no more chat.
Commands get passed with no problems, however chat doesn't show up. Spamfilters (BungeeChatFilter; removing it doesn't fix) are still triggering their messages as well. No trace of me trying to chat appears in the console on bungeecord or the server(s).

I believe it could be related to what was mentioned in this update:
http://www.spigotmc.org/resources/cloudchat.266/update?update=1426

CloudChat Report while trying to say something (as player and admin/op):
http://pastebin.com/wa5VCtwc

BungeeStartup (no errors)
http://pastebin.com/4Q71zzJv

**Comment by Absentee23** [comment]
After more testing, I found I am able to send chat by using '/g texthere,' despite PrivateMode being set to 'false.' Is there another setting like that I am missing, like a channel setting?

**Comment by Absentee23** [comment]
I'm gonna close this. The issue seemed to be I was stuck with the "ignored" flag set to "true" in my user data. /cc:unmute didn't seem to work, thought I could be mistaken. Stopping bungee and manually changing the flag to false fixed it, and now /cc:mute and /cc:unmute seem to work fine.

**Comment by geNAZt** [comment]
How did the ignore Flag come into that ? It is currently impossible to get it in a normal way oO

**Comment by geNAZt** [comment]
Fixed in https://github.com/geNAZt/CloudChatBukkit/commit/acfba504a1ecac46213c5520608f76bccdb9615f
And https://github.com/geNAZt/CloudChat/commit/3ef18f1b0c3879874bc94c33e15794f04266a967
