### ISSUE TITLE
URL's broken.

### ISSUE THREAD

**Issue by roblikescake** [geNAZt/CloudChat#53]
When a user posts a url in chat, such as: http://pastebin.com/9DabDzem and you click to  get asked to open it or not, the same link shows up, however when it actually opens up the url, it opens up <link>§r such as http://pastebin.com/9DabDzem§r

I attempted to check where you handle url's in the plugin, but was unsuccessful in my search.

**Comment by geNAZt** [comment]
Fixed in https://github.com/Cube-Space/BungeeLib/commit/fbbc499c17165789b5204931c54c69f6ce6c592a
Downloadable Build: http://www.spigotmc.org/resources/bungeelib.316/ (1.5.4)
