### ISSUE TITLE
[Enhancement] Auto kick users from channels they have no permissions for.

### ISSUE THREAD

**Issue by TagCraftMC** [geNAZt/CloudChat#54]
This would be an option to enable, not something always enabled.

The issue mainly arises when you use a configuration setup that is/similar to http://www.spigotmc.org/wiki/cloudchat-server-channels/ .
If Player Joins serverA and gets channel.serverA permission and channel access than moves to serverB, he loses channel.severA permission in serverB and gets a big message about not having the permissions to enter that channel (as seen below)

![8124f36012e1b2a8e46547c282eb5cdc](https://f.cloud.github.com/assets/4666336/2339265/a776da06-a4b3-11e3-9d22-5a1ab412d3a7.png)

I feel a good away around this is adding an option that onjoin of a server onworldchange if you don't have permissions to be in a channel you're kicked out of it silently.

**Comment by geNAZt** [comment]
Fixed in here https://github.com/geNAZt/CloudChat/commit/4e9cc53af0f5329a26a3c0361620917d67cf0e07

Version is released

**Comment by TagCraftMC** [comment]
Thanks geNAZt.
