### ISSUE TITLE
[Enhancement] message.yml for /fchat

### ISSUE THREAD

**Issue by TagCraftMC** [geNAZt/CloudChat#56]
Not sure if this should be submitted under CCB, so I apologize if it should be.

This one is simple, allow use to edit the messages with /fchat command.
The reason behind it is I would just like to format them along with all the other text, as well as removing the "You now talk in Global" to something a little nicer like You're now chatting in Factions.

Thanks

**Comment by geNAZt** [comment]
Added in https://github.com/geNAZt/CloudChatBukkit/commit/66098e7afe1c7886393fad54110204330fe410b0

Download: http://www.spigotmc.org/resources/cloudchatbukkit.265/
