### ISSUE TITLE
[Enhancement] cc:reload refreshes messages.yml

### ISSUE THREAD

**Issue by TagCraftMC** [geNAZt/CloudChat#57]
Pretty simple request, cc:reload also re-loaded the changes in messages.yml.

Reason is we have a semi-popular server and restarting the proxy annoys a lot of the users. We would love to be able to make edits on the fly.

Thanks

**Comment by geNAZt** [comment]
cc:reload does reload the Messages. In what cases does this not work ?

**Comment by TagCraftMC** [comment]
All of the case. It does not re-fresh any of the changes done in messages.yml.

I hope the image helps.

![9b1e53c3cb8d67a11f9a0c4f48a6e330](https://f.cloud.github.com/assets/4666336/2352697/7859d614-a590-11e3-8361-2303d9807ef9.png)

**Comment by geNAZt** [comment]
Fixed in https://github.com/Cube-Space/Yamler/commit/a48d0a41a09c18d25b02662716771556a17e3a41

Download: http://www.spigotmc.org/resources/yamler.315/
