### ISSUE TITLE
/cc:mute doesn't persist on relog

### ISSUE THREAD

**Issue by Absentee23** [geNAZt/CloudChat#58]
I've tried to permanently mute someone with /cc:mute to remove their chat privileges after they've been spamming, however as soon as they log out and log back in they are unmuted and able to speak again. There are no errors in the console.

Also, maybe have a configurable notification on global mute? "Silent" to say nothing except to the admin/mod that muted someone. "Private" to tell only the person that was muted, and to say how long they were muted for. "Public" to announce to everyone that they were muted.

**Comment by geNAZt** [comment]
Global Mutes should be persisted. Can you paste the Players Database. There should be a Muted: true and a MutedFor: 0 entry.

For the Rest: Only for the Global Mutes. The private Mutes only get shown by the muter and not the muted.

**Comment by Absentee23** [comment]
Muted always shows false and MutedFor shows 0 regarless of if I permanently mute them (by not adding a time) as well as when adding a mutedfor time. Bungee console shows just this, no errors:

```
23:31:23 [INFO] [CloudChat] Absentee23 emitted command: cc:mute with args petalsper
23:31:23 [INFO] [CloudChat] Absentee23 globally muted PetalsPer
```

It seems its not updating the database file, permissions are OK.

**Comment by geNAZt** [comment]
The Database Files only get updated when the owner of the File (the Player) leaves

**Comment by Absentee23** [comment]
It's not getting updated at all. Just tested like this: check file (muted:false), muted player, check file again (no change), have player leave, check file again (no change), have player rejoin, check file again with no change.

I missed this before, I see this on player logout, but other than that, nothing:

```
23:38:19 [WARNING] [CloudChat] Could not send Message because the PlayerDatabase has been unloaded
```
