### ISSUE TITLE
[Enhancement] Local channel being a channel

### ISSUE THREAD

**Issue by Hatventures** [geNAZt/CloudChat#60]
From what I understand, right now the way cloudchat handles local is to send any and all message at anyone within the radius (and of course, has to be in the same chan yada yada).

While I can imagine one or two cases that could use this kind of settings, I feel it missed its target!

dimensionZ's local (well, really, any local chat in a bukkit plugin since forever):

Either:
-  Force a channel called "local" that acts with the indicated range.
  or
- Give a range option to any and all channels (allowing us to create local on our own, and other proximity channels if required).

(Sorry for the tickets, but I'd rather tell you what I think should be changed/fixed :))

**Comment by Hatventures** [comment]
(mmmh, this maybe should have been in the cloudchatbukkit part. duh)

**Comment by geNAZt** [comment]
I don't understand what you mean :o: 

When someone local Chats the current Focused Channel of that Player is choosen. You want to have extra Channels for that (like Towny and Factions get handled) ?

Also the multiple Range thing would cause double/more Messages if i understood that correctly ?

And for the CCB part. Wayne you could post a issue in geSuit for CloudChat and i would fix it (i dare you todo that. i double dare you !)

**Comment by Hatventures** [comment]
Well as far as i've noticed is that as soon as you set a server with cloudchatbukkit config" use local true and set a distance, EVERY channels are "local".

The way i've always seen it work is to have a dedicated local channel that has a specific range

**Comment by geNAZt** [comment]
So how would you like to handle that ? I could create a "local" Channel which gets used. But then you can not focus into other Channels (while in the local chat server). Another solution would be to refocus the Player into the local Channel once he/she enters the Local Chat Server and let the User refocus when he wants out of the Local Chat.

**Comment by Hatventures** [comment]
Had to reply from the train:

To me focus is just the current channel where your command-less chat goes to, right?

If so local is no diferent from other channels. Just have a radius modifier

**Comment by geNAZt** [comment]
Correct

**Comment by Hatventures** [comment]
Sois it possible to have it that way ?(aka line bungeesuitechat/herochat/anybukkitchatwithlocal)?

Awesome update speed mate. Impressed

**Comment by Hatventures** [comment]
Well yeah i'm drunk, sorry for the typos

**Comment by geNAZt** [comment]
We can talk about that in IRC once you are ready to talk :D

**Comment by Hatventures** [comment]
Alright! Let's try and make sense of it all!

## Here is how I beleive it works NOW

(server set with local enabled, 50 blocks radius - 2 players in the server - Global / Local / Admin chans)

**Player1 & Player2 are next to each other**
Player1 sends:
- hey!
- /g ho!
- /l ha!

_Player 2 receives it all._

**Player2 moves away (+100 blocks or change world)**
Player1 sends:
- hey!
- /g ho!
- /l ha!

_Player2 sees nothing._

Conclusion: When enabled, the "use local" option forces ALL the channels to be based on a radius around the sender.

## What I was trying to say all along

(server set with a local channel with 50 blocks radius - 2 players in the server - Global / Local / Admin chans)

**Player1 & Player2 are next to each other**
Player1 sends:
- hey!
- /g ho!
- /l ha!

_Player 2 receives it all._

**Player2 moves away (+100 blocks or change world)**
Player1 sends:
- hey!
- /g ho!
- /l ha!

_Player2 receives the first 2 global messages, but is too far to receive Player1 local message (50blocks+ or different world)_

Conclusion: Only local (could be a static channel that is always there when local is enabled on server, or even an option in the channels settings) is affected by the radius limitation.
I hope this help us finally understand each other <3

**Comment by geNAZt** [comment]
Ah i see. So like Factions and Towny handle it. A non focusable Channel for Local Messages

**Comment by Hatventures** [comment]
Dont see why it wouldnt be able to be focusable. But townychat was a pretty good plugin, command/feel like.

I like being able to

Talk in global!
/l Send a quick message to local
/l
Focus on local
/a
Switch to admin
/g send a quick message to global

And obviously, keep receiving all the messages in any "joined" channel.

Then again, that could just be _me_. YOu are free to tell me "wtf dood, your way suck!" <3

**Comment by geNAZt** [comment]
Well the problem is that CloudChat does not know who is in which range :D

**Comment by Hatventures** [comment]
Well that is a problem indeed. Since local is bound to cloudchatbukkit, certainly cloudchatbukkit knows. Could send the relative (aka, in the radius) player names as an extra informations to cloudchat.

If that's too much out of the scope of your plugin, I'm sure I could write up my own little plugin that would do just that, and that way no more annoying frenchman's ticket :P 

<3

**Comment by Hatventures** [comment]
(If out of context, maybe you could even add a way to add remote filters easily, that way people could extend channel functionalities!)
