### ISSUE TITLE
[Bug] Spam "you cannot join more channels .."

### ISSUE THREAD

**Issue by Hatventures** [geNAZt/CloudChat#61]
Config:
MaxChannelsPerChatter: 3

Channels created : 3
Channels joined (with perms) : 3

Whenever i change world, 3x You cant join this channel.

I guess the forcejoin is a tad too trigger-happy. 

Also, I feel that this message should only happen upon request (/join command) allowing a natural feedback. Getting that kind of messages upon join or any other event just makes the player confused.

<3

**Comment by Hatventures** [comment]
Still getting the same "You cant join this Channe; ..." (times 3) when connecting, changing world ...

Using latest CC & CCbukkit (I am quite certain i saw that change in the changelog, but maybe i'm reading it wrong and it's actually not released yet. In that case ignore teh frenchman)

**Comment by geNAZt** [comment]
If the current Solution which i released (in 5.0.0+) does not work as wanted the Bug persits
