### ISSUE TITLE
 [Enhancement] social spy showing % sign

### ISSUE THREAD

**Issue by ammarx** [geNAZt/CloudChat#64]
Hello, I have a request. Can the %server variable be added to the social spy class. 
![2014-03-09_18 30 04](https://f.cloud.github.com/assets/4668212/2368010/61532f78-a78f-11e3-8700-fdc9c024dfe5.png)

Here is an example in while I am in the lobby(gateway) server with chatspy (socialspy) on and I am looking at people that are in another server and /msg messaging each other.

Regards,
Ammar Ahmad
TagCraftMC Staff

**Comment by TagCraftMC** [comment]
What Ammar is trying to ask is for the %server variable to be added to social spy class as well.
Thanks
