### ISSUE TITLE
[Bug] FocusChannel firing twice & Lower cased.

### ISSUE THREAD

**Issue by TagCraftMC** [geNAZt/CloudChat#65]
Not a massive/important bug.

It seems FocusChannel: messages are firing twice on server join.
    Focus:
      FocusChannel: '&6You''re now chatting in the &a%channel &6Channel'
![983b0d8e3146f617d70d48a1cfe5525d](https://f.cloud.github.com/assets/4666336/2370768/9c54c72c-a810-11e3-8a61-8cae21195dda.png)

The other small issue is that it gets the lowercase name of the channel on server join, but when you use /focus channelname it's proper casing.
![a10b7c3835743876d53b88d392728cd6](https://f.cloud.github.com/assets/4666336/2370772/df6c61fa-a810-11e3-8d20-b513a94d630c.png)

Thanks

**Comment by geNAZt** [comment]
Is this still happening

**Comment by TagCraftMC** [comment]
I will try to roll out an update today and let you know.

**Comment by TagCraftMC** [comment]
Although a bit late (sorry been busy) this issue does not seem to be fixed running;
CC: 6.1.1
CCB: 2.0.1
YAMLER Bukkit: 2.0.0
YAMLER Bungee: 1.5.2 
BungeeLib: 1.6.1
