### ISSUE TITLE
[BUG] No chat showing

### ISSUE THREAD

**Issue by tierdal** [geNAZt/CloudChat#68]
This is a new issue that arose after the update.

One of my servers (Factions) just stopped showing user messages.
WHAT I MEAN:
I go to Factions server. Have global channel focused. Try talking. Nothing is displaying, but Bungee Console shows that i did say something. No one else can see that message but the console. I can see everyone's messages from all other servers but Factions. I try /global MESSAGE and it works, everyone can see it and everything. Same is with other channels that I try, and it's only for that one server. Everything else works as it is supposed to.

You already know of the other issue of forcing the channels so I wont waste more time. Help, please.

**Comment by geNAZt** [comment]
Can you generate me a Report ? Also please post the relevant Channel Configs

**Comment by tierdal** [comment]
wrong button... give me a moment to get all the necessary files ready

**Comment by tierdal** [comment]
http://rise.risenkingdoms.com/CloudChatReport.txt

i have no clue what is wrong..

**Comment by geNAZt** [comment]
Which faction Chatmode is that ?

**Comment by tierdal** [comment]
its in Global... when they talk in Faction Mode they can actually see their chat, but the actual channels like global or local or server channel dont show up anywhere but the bungee console
