### ISSUE TITLE
admins with '*' permissions cannot use any channels

### ISSUE THREAD

**Issue by tierdal** [geNAZt/CloudChat#69]
just as the title says... all my regular users can talk and such, but me and other admins cannot write in any channels

**Comment by geNAZt** [comment]
Thats correct because cloudchat has a cloudchat.cannot.write.<channel> permission which is included in *

**Comment by tierdal** [comment]
so how would i get around it? negating the permission did not work... or do I need to negate it in the cloudchat.rank.admin permission block?

**Comment by geNAZt** [comment]
If you need to negate the Permission i need to build a fix in the BungeeLib for that.

**Comment by geNAZt** [comment]
https://github.com/Cube-Space/BungeeLib/commit/fc42b605cba69532086583e287adc068259995a2
