### ISSUE TITLE
[Bug] afk is not cancelled on player chat when using /CHANNELNAME msg

### ISSUE THREAD

**Issue by Hatventures** [geNAZt/CloudChat#71]
When using
/<somechannel> <msg>
you do not leave your afk status

<3

**Comment by geNAZt** [comment]
https://github.com/geNAZt/CloudChat/commit/49b5ced3f37d1f37bcf00be71f613d67ae5f0cee

**Comment by geNAZt** [comment]
https://github.com/geNAZt/CloudChatBukkit/commit/74bf405940a7cc543f80e94c32f0c5c6c260f609
