### ISSUE TITLE
CloudChat Channel and /mail /msg /reply Permissions

### ISSUE THREAD

**Issue by mcConspirators** [geNAZt/CloudChat#74]
Do the perms need to be added to the BungeeCord server or the Spigot/Bukkit server?

**Comment by geNAZt** [comment]
"BungeeCord/Bukkit Permissions (works either way)" - The resource Description

**Comment by mcConspirators** [comment]
The only thing I've gotten working, so far as permissions are concerned are players being able to use a second channel. /mail /msg /reply are still broken. I've put the perms in Bungee, and then tried on Bukkit, then did both. Still got nothing, so somebody is lying.

**Comment by geNAZt** [comment]
Then you give the wrong permissions. What permissions do you give ?

**Comment by mcConspirators** [comment]
cloudchat.command.msg
cloudchat.command.reply
cloudchat.command.mail

Those are the 3 permissions.

**Comment by mcConspirators** [comment]
Are those the correct 3 I should be using or is it another permission I'm not aware of?
