### ISSUE TITLE
When OP "Can't Write in this channel" message

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#77]
When I op in my minigames server that message appears, however that only happens in my minigames server. When I deop and rejoin I can speak normally which is weird

**Comment by geNAZt** [comment]
The permission manager in Bukkit gives you all permissions when using OP Status. So it also gives you "cloudchat.cannot.write._". If you don't want that revoke this Permission from you "-cloudchat.cannot.write._" or "cloudchat.cannot.write.*" to false in some Permission managers
