### ISSUE TITLE
[Request] [Irc] Mute IRC or a Single nick of IRC

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#78]
Could you add a command to mute someone from the IRC?

like /irc:mute (nickfromirc)

or if not possible a command to mute global IRC.

To stop spamming ^^

**Comment by geNAZt** [comment]
Muting a Player in IRC is not possible (since the bot is not op in the most cases).

A IRC mute is possible

**Comment by geNAZt** [comment]
Added in 8.1.0

**Comment by IlPicasso** [comment]
Good!

one more thing

Is it possible to ignore messages from a player in irc to not be sent to the gamechat. (An alternative option if muting a player in irc is not possible)

This would make the player think that is spamming and he is not because his message will stay in IRC

**Comment by geNAZt** [comment]
This is not possible since IRC Nicks can change every time
