### ISSUE TITLE
support for /mute

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#8]
- as global command
  
  /mute < player> [time to be muted]
- per server; the CloudChatBukkit could inform CloudChat when players are being muted/unmuted, or the command could be 
  
  /mute < player>  [time to be muted] [on] < server>
- maybe extend it to the IRCchannels by either muting the IRCentity or not delivering Messages from it

**Comment by geNAZt** [comment]
Added this:
- /mute <player> - Mutes the Player <player> for you - Permission: cloudchat.command.mute
- /unmute <player> - Unmutes the Player <player> you - Permission: cloudchat.command.unmute
- /cc:mute <player> - Globally mutes the Player <player> (also for IRC) - Permission: cloudchat.command.cc.mute
- /cc:unmute <player> - Globally unmutes the Player (does not revert /mute mutes) - Permission: cloudchat.command.cc.unmute
