### ISSUE TITLE
DoubleChat only in Survival server

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#80]
Everything worked fine until this morning. Started getting double messages

http://gyazo.com/ab7933488aa681c253266af4ab3c37ff

**Comment by IlPicasso** [comment]
It is only happening in the survival server while in every other server is just fine

**Comment by geNAZt** [comment]
Do you have factions ? Also did CloudChatBukkit die ?

**Comment by IlPicasso** [comment]
In the server I have factions Is workin well I am using a modified version in the factions server. Cloud chatbukkit is still enabled

**Comment by IlPicasso** [comment]
my fault, I am sorry I added by mistake mcore to my survival server.
