### ISSUE TITLE
LocalChat suddenly breaks for some players in one of my servers

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#82]
Today a few players were getting this issue of not beign able to talk in local chat but in others they could. 

I catched the error, however my cloudchat didn't had the last CloudChatBukkit and CloudChat. I thought that by updating it error could dissapear.

Now I found a player is having that issue again in the same server (survival) before updating an error was sent to the console, with the new build no error appears however I could catch the error log when using the last build

http://pastebin.com/z8pENznF

For some reason when I tp to them the issue dissapears but when I leave they get the problem again

**Comment by geNAZt** [comment]
Wrond commit, but this issue is also fixed :D

**Comment by IlPicasso** [comment]
luv u
