### ISSUE TITLE
Permissions of cloudchat breaks after getting kicked in my MyZ server

### ISSUE THREAD

**Issue by IlPicasso** [geNAZt/CloudChat#88]
It onyl breaks for me 

http://pastebin.com/KPfmfpAh

**Comment by IlPicasso** [comment]
it only breaks for my users and it generates a really long long error log that spams my console

**Comment by geNAZt** [comment]
Can you please test this BungeeLib build: http://jenkins.cube-space.net/job/BungeeLib/3/artifact/target/Cubespace-BungeeLib.jar

**Comment by IlPicasso** [comment]
I just saw this, Sorry, 

I didn´t had this issue anymore 

Thanks!
