### ISSUE TITLE
Players aren't joining global chat on login

### ISSUE THREAD

**Issue by LizzyTheDJ** [geNAZt/CloudChat#90]
I can't get players to automatically join global chat. Also, once a player types '/join global' messages only appear in global chat with a '/g message' format.

**Comment by Absentee23** [comment]
Same here. Global channel is forced and players have permission for it. Players ARE able to chat, it shows up for other players, but it does not appear to themselves, and they can't see others' messages, so it appears to them as if their chat never appears.

having them run `/join global` fixes it

Do channels now _need_ to be listed in joinOrder.yml?

There's also another issue open for this it looks like.

**Comment by LizzyTheDJ** [comment]
I want Global to be forced. Any idea how you managed that?

**Comment by geNAZt** [comment]
joinOrder.yml

**Comment by Absentee23** [comment]
I'm seeing this error, and immediately after, players are no longer put in global on join. Up until that point, it was working as expected. Possible conflict with geSuit?

http://pastebin.com/Kb6Adf4w

**Comment by LizzyTheDJ** [comment]
I've set the joinOrder so that each server they first join the local chat, then the global chat. I've also listed it as just the global chat, and neither is working for me.

**Comment by Absentee23** [comment]
> I want Global to be forced. Any idea how you managed that?

To force a channel (so they can't leave it without permissions), change forced to true in the channelname.yml file.

**Comment by LizzyTheDJ** [comment]
joinOrder.yml: http://pastebin.com/5Tfx1uis

global.yml: http://pastebin.com/58vG4yqm

I just want everyone to be able to chat to everyone all the time.

**Comment by Absentee23** [comment]
From the cloudchat description page: (adapted for your server names)
joinOrder.yml:
`For Lobby first check local, then global`
`It will stop when it hits the first Channel a Player can join.`

Check your bungee console on player join. If global is forced (as your global.yml is) it is likely players are joining the channel, but focusing local because of your joinOrder.yml, even though focusonjoin is set to true for global.

Probably better to ask a question like this on the spigot discussion for cloudchat, fyi.

**Comment by LizzyTheDJ** [comment]
As I said earlier, I've tried listing them as just global. I've checked in console and no one is joining the channel without manually entering /join global

Where is that?

**Comment by Absentee23** [comment]
The discussion page is [here](http://www.spigotmc.org/resources/cloudchat.266/), for setup questions, etc. If you aren't getting errors along with a player joining (like `[SEVERE] [CloudChat] Could not get Player Database for PLAYERNAME`, for example, which is the one I get when they aren't joining global on login, except my symptoms are intermittent) then it is likely a config issue. Whats your config.yml look like, specifically is `LogChannelActions: true` (to show join/leaves in console, can get spammy but is useful for debugging)?

Try running `/cc:report on` just before someone joins, and see if you get any errors, it will save a report file in the CloudChat plugin folder in `reports`.

**Comment by LizzyTheDJ** [comment]
My config.yml looks like this; http://pastebin.com/VZJsEMWA
And there's no errors when people are joining: http://pastebin.com/E4sx24Qf

Sorry, new to this. I can move myself there unless you can tell me something really obvious I'm missing.

**Comment by geNAZt** [comment]
It seems like CCB does not send a Permission set back so the Player can't get joined because CloudChat does not know which Permissions a Player has. Please check the CCB setup or paste a longer Report

**Comment by LizzyTheDJ** [comment]
Sorry again for posting this here and wasting y'alls time. I got the person who created the server to look at it and my issues fixed. I'll go to the correct place in future.

<3

**Comment by mcraftpete** [comment]
how did u fix it lizzy , I have the same thing , and all my files look like yours.i am assuming it is something bukkit side as genazt has said ?

**Comment by mcraftpete** [comment]
BlockPlayerJoin: false
BlockPlayerQuit: false
HandleAFK: false
AutoAFK: 0
Cooldown:
  # Cooldown in seconds
  AFKCommand: 0

# Relay chat into logs

LogChat: false
Worlds:
  testWorld: TW
AnnounceFactionModeOnJoin: true
DefaultFactionMode: global
FactionModes:
  geNAZt: faction

This is my cloudbukkitconfig , do I have to list the worlds above ? and how ?
Worlds:
    testworld :  whatsthisbithere ?
