### ISSUE TITLE
Chat to channel with ! or @ oder # infront of text 

### ISSUE THREAD

**Issue by fkreiner** [geNAZt/CloudChat#91]
I really would like a feature which allows to chat into channel by putting a preconfigured letter infront of the text. Example: "!I´m looking for some diamonds" goes to Global or something like that.

Greeting Flo
~f70r1an

**Comment by geNAZt** [comment]
This would lead to confusion in Command handling inside Bungee since i have to block all messages which contain those Prefixes (! for example is a console command in geSuit)
