### ISSUE TITLE
Join and leave message persist even when disabled

### ISSUE THREAD

**Issue by ravand1990** [geNAZt/CloudChat#93]
config.yml:
Announce:
  PlayerJoin: false
  PlayerQuit: false

messages.yml:
PlayerJoin: ''
PlayerQuit: ''

server config.yml:
BlockPlayerJoin: true
BlockPlayerQuit: true

Still getting spamed with join and leave messages :/ and the annoying thing abou it is, you even get them when people change the world

Am i missing something?
Thanks in advance

**Comment by geNAZt** [comment]
Yeah its not from this Plugin :)
