### ISSUE TITLE
[Info] Please advise formatting for Private Messaging

### ISSUE THREAD

**Issue by TheLecturer** [geNAZt/CloudChat#94]
Hi.  Switching to Cloud Chat from BungeeSuite.

I have been able to duplicate my previous chat formatting by editing /plugins/CloudChat/database/channels/global.yml.  All good.

However I can't seem to find a way to change the formatting for when players use private messages - I have found the following in /plugins/CloudChat/messages.yml -

```
Message:
  Sender: '&6You&8 -> &6%receiver&8:&7 %message'
  Receiver: '&6%sender&8 -> &6You&8:&7 %message'
```

%receiver and %sender seem to be placeholders / shortcuts for the default formatting string (e.g. '&8[&2%channel_short&8] %prefix%nick{click:playerMenu}%suffix&r:' or something similar).

Could you please advise if / how I can change the formatting of %receiver and %sender.

Many thanks.

**Comment by geNAZt** [comment]
Message:
  Nick:

**Comment by TheLecturer** [comment]
Thanks.
Just FYI, changing "Nick:" to a blank entry didn't work as it was just recreated with the default settings.
However changing it to "Nick: &nick" gave the desired outcome.
