### ISSUE TITLE
IRC joining a secured room (password or invite)

### ISSUE THREAD

**Issue by eledore** [geNAZt/CloudChat#99]
We would like to have our 'Staff' channel report to a IRC room 
But would not like everyone to be able to join this room only our staff members.

This can be achieved by; 
Either by password protecting this room (/join #room (password)
Or set to the room invite only and allow the bot in trough chanserv (/cs invite #room)

Currently CloudChat does not allow either.
I think simplest sollution would to allow joining of a password protected room. While i would love the other option more.

**Comment by geNAZt** [comment]
CloudChat supports Channel passwords. "#channel password" needs to be used in the IRC config.

**Comment by eledore** [comment]
Cant believe i didn't just try it.
Atleast add it to the irc.yml documentation, so the next one with this issue knows how to solve it.

Thanks for the great plugin.
